openapi: 3.2.0
info:
  title: APMs Operational API
  description: Pay using eWallets, bank transfers, direct debits, local card schemes, Postpay and eInvoice/ Buy Now Pay Later.
  version: '2024-07-01'
  x-metadata:
    category:
    - Alternative Payments
    business:
    - Enterprise
    catalog-list: true
    generated: false
  x-logo:
    url: worldpay-logo.svg
servers:
- description: Test (Try)
  url: https://try.access.worldpay.com
- description: Live
  url: https://access.worldpay.com
security:
- BasicAuth: []
tags:
- name: Operational
paths:
  /apmPayments/status:
    get:
      operationId: status
      responses:
        '200':
          content:
            '*/*':
              example: OK - 2022-05-16T10:50:55.444486
              schema:
                type: string
          description: The status of the service is OK.
        '400':
          $ref: '#/components/schemas/AccessApiValidationError'
      summary: Used to check whether the service is up
      tags:
      - Operational
components:
  schemas:
    AccessApiValidationError:
      description: Validation error object.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
